const quoteTag = document.getElementById("quote");
const usedIndexes = new Set();
const quotes = [
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "Don’t watch the clock; do what it does. Keep going.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Dream big. Start small. Act now.",
  "Great things never come from comfort zones.",
  "Push yourself, because no one else is going to do it for you.",
  "The secret of getting ahead is getting started.",
  "Believe you can and you're halfway there.",
  "Don’t limit your challenges. Challenge your limits.",
  "In the middle of every difficulty lies opportunity.",
  "Life is either a daring adventure or nothing at all.",
  "Happiness is not something ready-made. It comes from your own actions.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "You only live once, but if you do it right, once is enough.",
  "The best way to predict the future is to create it.",
  "Life isn’t about finding yourself. Life is about creating yourself.",
  "Difficult roads often lead to beautiful destinations.",
  "Life is short. Smile while you still have teeth.",
  "A smooth sea never made a skilled sailor.",
  "Love is composed of a single soul inhabiting two bodies.",
  "A friend is someone who knows all about you and still loves you.",
  "Where there is love, there is life.",
  "The best thing to hold onto in life is each other.",
  "True love stories never have endings.",
  "Friendship is born at that moment when one person says to another: 'What! You too? I thought I was the only one.'",
  "We loved with a love that was more than love.",
  "In the end, we only regret the chances we didn’t take and the love we didn’t give.",
  "To love and be loved is to feel the sun from both sides.",
  "You don’t find love, it finds you. It’s got a little bit to do with destiny, fate, and what’s written in the stars.",
  "Change your thoughts and you change your world.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "It always seems impossible until it’s done.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Challenges are what make life interesting, and overcoming them is what makes life meaningful.",
  "Your only limit is your mind.",
  "A champion is defined not by their wins but by how they can recover when they fall.",
  "Growth is painful. Change is painful. But nothing is as painful as staying stuck somewhere you don’t belong.",
  "The mind is everything. What you think you become.",
  "Small steps in the right direction can turn out to be the biggest step of your life.",
  "Stay hungry. Stay foolish.",
  "Dream it. Wish it. Do it.",
  "Don’t stop until you’re proud.",
  "Be the energy you want to attract.",
  "Make it happen.",
  "You are stronger than you think.",
  "Turn dreams into plans.",
  "Act as if what you do makes a difference. It does.",
  "Focus on the good.",
  "Less talking, more doing.",
  "The only joy in the world is to begin.",
  "Positive anything is better than negative nothing.",
  "Choose kindness and laugh often.",
  "The sun himself is weak when he first rises, and gathers strength and courage as the day gets on.",
  "Happiness depends upon ourselves.",
  "Joy is not in things; it is in us.",
  "Let your smile change the world, but don’t let the world change your smile.",
  "Stay close to anything that makes you glad you are alive.",
  "Do more things that make you forget to check your phone.",
  "Happiness is a journey, not a destination.",
  "Shoot for the moon. Even if you miss, you’ll land among the stars.",
  "If your dreams don’t scare you, they’re too small.",
  "Dream big and dare to fail.",
  "All our dreams can come true if we have the courage to pursue them.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Follow your dreams, they know the way.",
  "Big dreams have small beginnings.",
  "Dreams don’t work unless you do.",
  "Success is dreaming, planning, and believing.",
  "Wake up with determination. Go to bed with satisfaction.",
  "He who has a why to live can bear almost any how.",
  "Knowing yourself is the beginning of all wisdom.",
  "An unexamined life is not worth living.",
  "We do not remember days, we remember moments.",
  "Everything you can imagine is real.",
  "Silence is sometimes the best answer.",
  "The soul always knows what to do to heal itself. The challenge is to silence the mind.",
  "The meaning of life is to give life meaning.",
  "Be yourself; everyone else is already taken.",
  "The best view comes after the hardest climb.",
  "Leadership is the capacity to translate vision into reality.",
  "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'",
  "A leader is one who knows the way, goes the way, and shows the way.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "You miss 100% of the shots you don't take.",
  "Fortune favors the bold.",
  "If you want to lift yourself up, lift up someone else.",
  "Bravery is the solution to regret.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Hope is being able to see that there is light despite all the darkness.",
  "Faith is taking the first step even when you don’t see the whole staircase.",
  "Once you choose hope, anything is possible.",
  "Let your hopes, not your hurts, shape your future.",
  "Hope is the heartbeat of the soul.",
  "Believe in miracles.",
  "Everything will be okay in the end. If it’s not okay, it’s not the end.",
  "Hope sees the invisible, feels the intangible, and achieves the impossible.",
  "Stars can’t shine without darkness.",
  "Never lose hope. You never know what tomorrow may bring.",
  "Whatever you are, be a good one.",
  "Keep going. Everything you need will come to you at the perfect time.",
  "Success is liking yourself, liking what you do, and liking how you do it.",
  "Sometimes you win, sometimes you learn.",
  "Success is a series of small wins.",
  "Every day is a second chance.",
  "Doubt kills more dreams than failure ever will.",
  "The future depends on what you do today.",
  "Work hard in silence, let success make the noise.",
  "Start where you are. Use what you have. Do what you can.",
  "Hustle until your haters ask if you’re hiring.",
  "Strength grows in the moments when you think you can’t go on but you keep going.",
  "The key to success is to start before you are ready.",
  "If it doesn't challenge you, it won't change you.",
  "Stay positive, work hard, make it happen.",
  "Your vibe attracts your tribe.",
  "If you want it, work for it.",
  "You are capable of amazing things.",
  "Progress, not perfection.",
  "Dream bigger. Do bigger.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Be so good they can’t ignore you.",
  "Don't wait for opportunity. Create it.",
  "Little by little, a little becomes a lot.",
  "One day or day one. You decide.",
  "Success is the sum of small efforts repeated day in and day out.",
  "Believe in yourself and all that you are.",
  "You don't have to be perfect to be amazing.",
  "Take the risk or lose the chance.",
  "Stop wishing. Start doing.",
  "Great things take time. Be patient.",
  "Failure is not the opposite of success; it’s part of success.",
  "Energy flows where attention goes.",
  "Your only competition is who you were yesterday.",
  "Difficult doesn't mean impossible.",
  "Do it with passion or not at all.",
  "Motivation gets you going. Discipline keeps you growing.",
  "Don’t be afraid to start over. It’s a brand new opportunity to rebuild what you truly want.",
  "Push harder than yesterday if you want a different tomorrow.",
  "Success is about creating value.",
  "You are one decision away from a completely different life.",
  "Action is the foundational key to all success.",
  "Small progress is still progress.",
  "Success starts with self-discipline.",
  "Winners are not afraid of losing. But losers are.",
  "Be brave enough to be bad at something new.",
  "Fall seven times, stand up eight.",
  "Don't quit. Suffer now and live the rest of your life as a champion.",
  "If you're tired, do it tired.",
  "Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.",
  "A river cuts through rock, not because of its power, but because of its persistence.",
  "One step at a time is good walking.",
  "You were born to be real, not perfect.",
  "The difference between ordinary and extraordinary is that little extra.",
];

function generate() {
  if (usedIndexes.size >= quotes.length) usedIndexes.clear();
  while (true) {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    if (usedIndexes.has(randomIndex)) continue;
    quoteTag.innerHTML = quotes[randomIndex];
    usedIndexes.add(randomIndex);
    break;
  }
}

function copyText() {
  const quote = document.getElementById("quote").textContent;
  navigator.clipboard
    .writeText(quote)
    .then(() => {
      console.log("Text copied to clipboard!");
    })
    .catch((err) => {
      console.error("Error copying text: ", err);
    });
}
